routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\CrudtagController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('crud', 'CrudtagController');

app/Crud.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class Crud extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'description', 'tags',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CrudtagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Crud;

class CrudtagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cruds = Crud::all();
        return view('view',compact('cruds'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('layouts.crud'); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $crud = new Crud([

        'title' => $request->get('title'),
        'description' => $request->get('description'),
        'tags' => $request->get('tags'),
       ]);
       $crud->save();

       return redirect('crud')->with('success', 'created Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $crud = Crud::find($id);
        return view('edit',compact('crud'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cruds = Crud::find($id);
        
        $cruds->title = $request->get('title');
        $cruds->description = $request->get('description');
        $cruds->tags = $request->get('tags');
        $cruds->save();
        return redirect('crud')->with('success', 'Update Successfully!');

    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cruds = Crud::find($id);
        $cruds->delete();
         return redirect('crud')->with('success', 'delete Successfully!');
    }
}

resources/views/edit.blade.php
@extends('layouts.app')
@section('content')
<h1>Edit Task</h1>
<hr>
<form action="{{ route('crud.update',$crud->id)}}" method="post">
@csrf
@method('PATCH');
    <div class="form-group">
        <label for="title">Task Title</label>
        <input type="text" class="form-control" id="taskTitle"  name="title" value="{{ $crud->title}}">
    </div>
    <div class="form-group">
        <label for="description">Task Description</label>
         <textarea type="text" class="form-control" name="description" rows="15" cols="135px" value="{{ $crud->description}}"></textarea>
     </div>
     <div class="form-group">
        <label for="tags">Task tag</label>
        <input type="text" class="form-control" id="taskTitle"  name="tags" value="{{ $crud->tags}}">
    </div>

   
    <button type="submit" class="btn btn-primary">Update</button>
    <button type="submit" class="btn btn-light">Reset</button>

</form>
@endsection

resources/views/layouts/app.blade.php
<html>
    <head>
        <title>App Name - @yield('title')</title>

        <link href="{{asset('css/style.css')}}" rel="stylesheet">
    </head>
    <body>

        <div class="container">
            @yield('content')
        </div>
        
    </body>
</html>

resources/views/layouts/crud.blade.php
@extends('layouts.app')
@section('content')
<h1>Add New Task</h1>
<hr>
<form action="{{ route('crud.store')}}" method="post">
@csrf
    <div class="form-group">
        <label for="title">Task Title</label>
        <input type="text" class="form-control" id="taskTitle"  name="title">
    </div>
    <div class="form-group">
        <label for="description">Task Description</label>
         <textarea type="text" class="form-control"  name="description" rows="15" cols="135px"></textarea>
     </div> 
     <div class="form-group">
        <label for="tags">Task tag</label>
        <input type="text" class="form-control" id="taskTitle"  name="tags">
    </div>

   
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

resources/views/view.blade.php
@extends('layouts.app')

@section('content')
@if(session('success'))
 <div class="alert alert-success" role="alert">
 	{{ session('success')}}
 	
 </div>
 @endif
 <a href="{{ route('crud.create')}}">Create Task</a>

 <div class="col-sm-12">
 	<div class="row">
 		<table class="table table-striped">
 			<thead>
 				<th>Id</th>
 				<th>Title</th>
 				<th>Description</th>
 				<th>Task tag</th>
 				<th>Edit</th>
 				<th>Delete</th>
 			</thead>
 			<tbody>
 				@if($cruds)
 				@foreach($cruds as $crud)
 				<tr>
 				<td>{{ $crud->id }}</td>
 				<td>{{ $crud->title }}</td>
 				<td>{{ $crud->description }}</td>
 				<td>{{ $crud->tags }}</td>
 				<td><a href="{{ route('crud.edit',$crud->id)}}" class="btn btn-light">Edit</a></td>
 				<td>
 					<form method="post" action="{{ route('crud.destroy',$crud->id)}}">
 						@csrf
 						@method('DELETE')
 						<button class="btn btn-danger" type="sumbit">Delete</button>
 					</form>
 					
 				</td>
 			</tr>
 				@endforeach
 				@endif
 			</tbody>
 			
 		</table>
 			
 			
 		</div>
 		
 	</div>
 	
 </div>
 @endsection